# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  name: 'Default' # Using a local agent running in Docker

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: SecurityScan
  displayName: Security Scan
  jobs:
  - job: TrivySecurityScan
    displayName: Trivy Security Scan job
    steps:
    - task: trivy@2
      inputs:
        method: 'system'
        type: 'filesystem'
        target: '$(Build.SourcesDirectory)'
        scanners: 'misconfig, secret, vuln'
        severities: 'CRITICAL'
        failOnSeverityThreshold: 'CRITICAL'
        reports: 'html'
        publish: true

- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
